import "./globals.css";
import { ThemeProvider } from "next-themes";
import { TaskProvider } from "./Components/contexts/TaskContext";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-white text-black">
        <TaskProvider>
        {children}
        </TaskProvider>
      </body>
    </html>
  );
}

